// ---------------------------------------------------------------------------
// Prodara Templates — Barrel Export
// ---------------------------------------------------------------------------

export { render, listTemplates, wrapForPlatform } from './renderer.js';
export {
  renderSpecify,
  renderClarify,
  renderPlan,
  renderImplement,
  renderReview,
  renderFix,
  renderExplore,
  renderHelp,
  renderParty,
  renderDesign,
  renderOnboard,
} from './phases/index.js';
export {
  renderArchitectureReview,
  renderSecurityReview,
  renderCodeQualityReview,
  renderTestQualityReview,
  renderUxQualityReview,
  renderCustomReview,
  renderAdversarialReview,
  renderEdgeCaseReview,
  ARCHITECTURE_PERSPECTIVE,
  SECURITY_PERSPECTIVE,
  CODE_QUALITY_PERSPECTIVE,
  TEST_QUALITY_PERSPECTIVE,
  UX_QUALITY_PERSPECTIVE,
  ADVERSARIAL_PERSPECTIVE,
  EDGE_CASE_PERSPECTIVE,
} from './reviewers/index.js';
export {
  wrapCopilot,
  wrapClaude,
  wrapCursor,
  wrapOpencode,
  wrapCodex,
  wrapGemini,
  wrapWindsurf,
  wrapKiro,
  wrapJules,
  wrapAmp,
  wrapRoo,
  wrapAider,
  wrapCline,
  wrapContinue,
  wrapZed,
  wrapBolt,
  wrapAide,
  wrapTrae,
  wrapAugment,
  wrapSourcegraph,
  wrapTabnine,
  wrapSupermaven,
  wrapVoid,
  wrapPear,
  wrapDouble,
  wrapGeneric,
  makeAdapter,
  COPILOT_DIR,
  COPILOT_EXT,
  CLAUDE_DIR,
  CLAUDE_EXT,
  CURSOR_DIR,
  CURSOR_EXT,
  OPENCODE_DIR,
  OPENCODE_EXT,
  CODEX_DIR,
  CODEX_EXT,
  GEMINI_DIR,
  GEMINI_EXT,
  WINDSURF_DIR,
  WINDSURF_EXT,
  KIRO_DIR,
  KIRO_EXT,
  JULES_DIR,
  JULES_EXT,
  AMP_DIR,
  AMP_EXT,
  ROO_DIR,
  ROO_EXT,
  AIDER_DIR,
  AIDER_EXT,
  CLINE_DIR,
  CLINE_EXT,
  CONTINUE_DIR,
  CONTINUE_EXT,
  ZED_DIR,
  ZED_EXT,
  BOLT_DIR,
  BOLT_EXT,
  AIDE_DIR,
  AIDE_EXT,
  TRAE_DIR,
  TRAE_EXT,
  AUGMENT_DIR,
  AUGMENT_EXT,
  SOURCEGRAPH_DIR,
  SOURCEGRAPH_EXT,
  TABNINE_DIR,
  TABNINE_EXT,
  SUPERMAVEN_DIR,
  SUPERMAVEN_EXT,
  VOID_DIR,
  VOID_EXT,
  PEAR_DIR,
  PEAR_EXT,
  DOUBLE_DIR,
  DOUBLE_EXT,
  GENERIC_DIR,
  GENERIC_EXT,
} from './platforms/index.js';
