// ---------------------------------------------------------------------------
// Prodara Compiler — Governance Engine
// ---------------------------------------------------------------------------
// Generates scoped agents.md files from the product graph and config.
// Never overwrites existing user-created agents.md files.

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { ProductGraph, ModuleNode } from '../graph/graph-types.js';
import type { ResolvedConfig } from '../config/config.js';
import type { GovernanceFile, GovernanceRule, GovernanceContext } from './types.js';

/**
 * Load the project-level constitution content from the configured path.
 * Returns `null` if no path is configured or file does not exist.
 *
 * Checks in order:
 * 1. Explicit path from `config.constitution.path`
 * 2. Default location `.prodara/constitution.md`
 */
export function loadConstitution(
  config: ResolvedConfig,
  root: string,
): string | null {
  // Explicit path from config
  if (config.constitution.path) {
    const resolved = join(root, config.constitution.path);
    if (existsSync(resolved)) {
      return readFileSync(resolved, 'utf-8');
    }
    return null;
  }

  // Default location
  const defaultPath = join(root, '.prodara', 'constitution.md');
  if (existsSync(defaultPath)) {
    return readFileSync(defaultPath, 'utf-8');
  }

  return null;
}

/**
 * Generate governance (agents.md) files from the product graph and config.
 * Returns files to write — caller is responsible for actual I/O.
 * Existing user-created files are never overwritten.
 */
export function generateGovernanceFiles(
  graph: ProductGraph,
  config: ResolvedConfig,
  root: string,
): GovernanceFile[] {
  const files: GovernanceFile[] = [];

  // Root agents.md — project-wide rules
  const rootPath = join(root, 'agents.md');
  if (!existsSync(rootPath)) {
    const context = extractGovernanceContext(graph, config);
    files.push({ path: rootPath, content: renderRootAgentsMd(graph, context) });
  } else {
    // Append Prodara workflow section if not already present
    const existing = readFileSync(rootPath, 'utf-8');
    if (!existing.includes('## Prodara Spec-Driven Workflow')) {
      files.push({ path: rootPath, content: existing + '\n' + renderProdaraWorkflowSection(graph) });
    }
  }

  // Per-module scoped agents.md
  for (const mod of graph.modules) {
    const modDir = resolveModuleDirectory(root, mod);
    /* v8 ignore next */
    if (!modDir) continue;
    const modAgentsPath = join(modDir, 'agents.md');
    if (!existsSync(modAgentsPath)) {
      files.push({ path: modAgentsPath, content: renderModuleAgentsMd(mod, graph) });
    }
  }

  return files;
}

/**
 * Read existing agents.md files from a project root.
 * Returns their rules as governance context for review enforcement.
 */
export function readGovernanceRules(root: string): GovernanceRule[] {
  const rules: GovernanceRule[] = [];
  const rootPath = join(root, 'agents.md');
  if (existsSync(rootPath)) {
    const content = readFileSync(rootPath, 'utf-8');
    rules.push(...parseGovernanceRules(content));
  }
  return rules;
}

// ---------------------------------------------------------------------------
// Context extraction
// ---------------------------------------------------------------------------

function extractGovernanceContext(
  graph: ProductGraph,
  config: ResolvedConfig,
): GovernanceContext {
  const techStack: string[] = [];
  const conventions: GovernanceRule[] = [];
  const testingPatterns: string[] = [];

  // Extract tech stack from product metadata
  if (graph.product.name) {
    techStack.push(`Product: ${graph.product.name}`);
  }

  // Extract reviewer-based conventions
  const reviewerNames = Object.keys(config.reviewers).filter(
    k => config.reviewers[k]?.enabled,
  );
  for (const name of reviewerNames) {
    conventions.push({
      category: 'constraint',
      rule: `Code must pass ${name} review`,
    });
  }

  // Extract testing patterns from configured validation
  if (config.validation.test) {
    testingPatterns.push(`Test command: ${config.validation.test}`);
  }
  if (config.validation.lint) {
    testingPatterns.push(`Lint command: ${config.validation.lint}`);
  }

  return { techStack, conventions, testingPatterns };
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

function renderRootAgentsMd(
  graph: ProductGraph,
  context: GovernanceContext,
): string {
  const lines: string[] = [];

  lines.push(`# ${graph.product.name} — Governance Rules`);
  lines.push('');
  lines.push('> Auto-generated by prodara. Customize as needed.');
  lines.push('');

  if (context.techStack.length > 0) {
    lines.push('## Tech Stack');
    lines.push('');
    for (const item of context.techStack) {
      lines.push(`- ${item}`);
    }
    lines.push('');
  }

  if (context.conventions.length > 0) {
    lines.push('## Conventions');
    lines.push('');
    for (const rule of context.conventions) {
      lines.push(`- **[${rule.category}]** ${rule.rule}`);
    }
    lines.push('');
  }

  if (context.testingPatterns.length > 0) {
    lines.push('## Testing');
    lines.push('');
    for (const pattern of context.testingPatterns) {
      lines.push(`- ${pattern}`);
    }
    lines.push('');
  }

  lines.push('## Modules');
  lines.push('');
  for (const mod of graph.modules) {
    lines.push(`- \`${mod.name}\``);
  }
  lines.push('');

  // Prodara workflow section
  lines.push(renderProdaraWorkflowSection(graph));

  return lines.join('\n');
}

function renderModuleAgentsMd(
  mod: ModuleNode,
  graph: ProductGraph,
): string {
  const lines: string[] = [];

  lines.push(`# ${mod.name} — Module Rules`);
  lines.push('');
  lines.push('> Auto-generated by prodara. Customize as needed.');
  lines.push('');

  // Module imports
  if (mod.imports.length > 0) {
    lines.push('## Dependencies');
    lines.push('');
    for (const imp of mod.imports) {
      lines.push(`- imports \`${imp.symbol}\` from \`${imp.from}\``);
    }
    lines.push('');
  }

  // Related edges
  const relatedEdges = graph.edges.filter(
    e => e.from.startsWith(mod.id + '.') || e.to.startsWith(mod.id + '.'),
  );
  if (relatedEdges.length > 0) {
    lines.push('## Relationships');
    lines.push('');
    for (const edge of relatedEdges) {
      lines.push(`- \`${edge.from}\` —[${edge.kind}]→ \`${edge.to}\``);
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Parsing
// ---------------------------------------------------------------------------

function parseGovernanceRules(content: string): GovernanceRule[] {
  const rules: GovernanceRule[] = [];
  const rulePattern = /^-\s+\*\*\[(\w+)\]\*\*\s+(.+)$/gm;
  let match: RegExpExecArray | null;
  while ((match = rulePattern.exec(content)) !== null) {
    const category = match[1] as GovernanceRule['category'];
    if (category === 'convention' || category === 'constraint' || category === 'preference') {
      rules.push({ category, rule: match[2]! });
    }
  }
  return rules;
}

// ---------------------------------------------------------------------------
// Prodara Workflow Section
// ---------------------------------------------------------------------------

function renderProdaraWorkflowSection(graph: ProductGraph): string {
  const lines: string[] = [];

  lines.push('## Prodara Spec-Driven Workflow');
  lines.push('');
  lines.push('This project uses [Prodara](https://www.prodara.net) for specification-driven development.');
  lines.push('');
  lines.push('### Workflow');
  lines.push('1. **Specify** — Create or edit `.prd` files to define the product');
  lines.push('2. **Validate** — Run `prodara validate` to check for errors');
  lines.push('3. **Plan** — Run `prodara plan` to generate an implementation plan');
  lines.push('4. **Implement** — Run `prodara build` to produce implementation instructions');
  lines.push('5. **Review** — Automated review loop checks architecture, security, and quality');
  lines.push('');
  lines.push('### CLI Commands');
  lines.push('| Command | Description |');
  lines.push('|---------|-------------|');
  lines.push('| `prodara build` | Full pipeline: compile → plan → implement → review |');
  lines.push('| `prodara validate` | Parse and validate .prd files |');
  lines.push('| `prodara graph` | Output the Product Graph |');
  lines.push('| `prodara plan` | Generate incremental implementation plan |');
  lines.push('| `prodara diff --semantic` | Show semantic diff from last build |');
  lines.push('| `prodara drift` | Check for specification drift |');
  lines.push('| `prodara explain <id>` | Explain a node in the product graph |');
  lines.push('');
  lines.push('### .prd Language Quick Reference');
  lines.push('- `product <name> { ... }` — Top-level product definition');
  lines.push('- `module <name> { ... }` — Logical grouping');
  lines.push('- `entity <name> { fields }` — Data model');
  lines.push('- `workflow <name> { steps }` — Business process');
  lines.push('- `surface <name> { sections }` — UI surface');
  lines.push('- Types: `string`, `int`, `float`, `boolean`, `uuid`, `datetime`, `money`');
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function resolveModuleDirectory(root: string, mod: ModuleNode): string | null {
  // Convention: module directory matches module name under the root
  const modDir = join(root, 'src', mod.name);
  // Only generate if the directory plausibly exists or will exist
  // For now, return the path — the caller (or generator) creates it
  return modDir;
}
